### ISSUE TITLE
SWA extension for new SWA isn't detecting local git repo

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurestaticwebapps#404] opened 2021-05-24 22:05 UTC
My .NET and JS testing for [this tutorial](https://docs.microsoft.com/en-us/azure/search/tutorial-csharp-deploy-static-web-app) gives me 1/8 steps when I select "Advanced" to create a SWA. 

@HeidiSteen uses the same tutorial steps but with a [Python version](https://github.com/Azure-Samples/azure-search-python-samples/tree/master/search-website) of the code and she gets either 12 or 13 steps - where she is asked for a repo, create a repo, etc. as if the extension doesn't recognize her local Git repo. What could be causing this? 

We need the steps to be proscriptive (completely repeatable) in the tutorial expecting 8 steps and not 12 or 13. 

@anthonychu @craigshoemaker Any ideas or help?

**Comment by nturinski** [comment] 2021-05-25 16:24
@diberry Thanks for reporting this.

The number of steps is dependent on whether or not the current local repo has a GitHub remote origin that the user has admin access to.  If @HeidiSteen is being asked to create a repo, it's likely because while she has a local repo, she needs to create a remote in GitHub for Static Web Apps to attach to and run GitHub Actions on.

The tutorial should definitely include either the step of creating/forking a repo from GitHub (8 step process) _or_ starting with a local repo with the expectation that a GitHub repo will be created (12 step process).  Also, the documentation is a bit old since we just changed the experience when the platform left preview.  [Here](https://github.com/microsoft/vscode-azurestaticwebapps/wiki/Creating-a-Static-Web-App) is a detailed description of the new creation process.

**Comment by diberry** [comment] 2021-05-25 16:41
@nturinski Can you work with @HeidiSteen internally to figure out where she went wrong. She successfully completed the same steps for the JS and .NET versions with a local fork of the repo which she owns - yet I didn't have any trouble and I don't own the origin repo, only my fork of it.

**Comment by HeidiSteen** [comment] 2021-05-25 16:54
@nturinski FYI that I'm using a remote origin that I own.  The repo I'm specifying in your wizard is https://github.com/HeidiSteen/azure-search-python-samples/tree/master/search-website -- which is my fork of the public repo.

**Comment by nturinski** [comment] 2021-05-25 18:33
I tried forking your repo https://github.com/nturinski/azure-search-python-samples.  I wasn't able to reproduce this with my workspace.

Our extension will only detect the remote repo if it has `origin` as the remote shortname.  Is it possible that your repo has named the remote something else?

**Comment by HeidiSteen** [comment] 2021-05-25 19:27
No, the remote short name is origin.  In your wizard, step 8, it won't accept "origin" (or any other value that I could think of to type in).  There is literally no way to progress in the wizard.

origin  https://github.com/HeidiSteen/azure-search-python-samples.git (fetch)
origin  https://github.com/HeidiSteen/azure-search-python-samples.git (push)
upstream        https://github.com/Azure-Samples/azure-search-python-samples.git (fetch)
upstream        https://github.com/Azure-Samples/azure-search-python-samples.git (push)

**Comment by nturinski** [comment] 2021-05-25 21:24
According to our remote naming rules, you should be able to name the remote anything that git will allow, but I'm assuming that you keep seeing the message `"RemoteName" is not a valid remote shortname.`?

We run a git command to verify that the name is valid.  I think that for some reason, in the python project, we aren't able to run git CLI commands for some reason.  That would also explain why we are not able to recognize that you have an "origin" remote because we utilize git for that as well.

> @nturinski Can you work with @HeidiSteen internally to figure out where she went wrong. She successfully completed the same steps for the JS and .NET versions with a local fork of the repo which she owns - yet I didn't have any trouble and I don't own the origin repo, only my fork of it.

Dina mentioned that you were able to complete this with the JS and .NET versions.  Are there any differences between the workspaces of these runtimes and Python?  Are you using a different work environment or anything like that?  What OS are you using?

**Comment by HeidiSteen** [comment] 2021-05-26 21:58
@nturinksi I was able to complete the wizard using the previous version of your extension.  I can't use the May release for any language: C#/NET, JS, Python.

**Comment by nturinski** [comment] 2021-05-26 22:42
@HeidiSteen Okay, thank you for that information.  Our new changes enforce some workspace configurations, and it seems that we are having issues accessing `git` through the VS Code terminal.  Do you know how you installed `git` on your machine?  If you type `which git` in your terminal, where did it install to?

**Comment by HeidiSteen** [comment] 2021-05-27 00:02
@nturinski  I installed Git Bash many years ago so I'm not sure.  For "which git":  /mingw64/bin/git

**Comment by diberry** [comment] 2021-05-27 12:39
SWA extension works for me - I'm using:

$ which git
/mingw64/bin/git

$ git --version
git version 2.30.1.windows.1

**Comment by HeidiSteen** [comment] 2021-05-27 16:00
I have this:  git version 2.17.1.windows.2   I'll see if I can get a newer git version.

**Comment by diberry** [comment] 2021-05-27 16:04
@nturinski Shoudl the extension be so picky about what version of git a customer is using?

**Comment by nturinski** [comment] 2021-05-27 16:12
No, the extension shouldn't care about what version of git the customer is using.  I was running an older version of git for a while and wasn't running into this 🤔

I'm not sure why, but it seems that we are having issues running git CLI commands through VS Code's shell.  We try to run `git` commands in the Windows temp directory, so it's possible that we don't have proper permissions to run those commands in Heidi's environment.

Rather than debugging Heidi's machine, I'll see what I can do on my end to make it more agnostic of these restrictions.  When I have a new build out, could @HeidiSteen install the new bits and re-try the tutorial?

**Comment by HeidiSteen** [comment] 2021-05-27 16:14
You bet -- just let me know when you have something you'd like me to try.   Thanks Nathan for persevering on this.

**Comment by nturinski** [comment] 2021-06-03 20:16
Hi @HeidiSteen

I have made some changes to the extension.  If you could give this a shot and see if it resolves this issue, that'd be great!

You can download the new bits here: https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5177059/vsix?itemPath=vsix%2Fvscode-azurestaticwebapps-0.7.1-alpha.vsix

Once you have downloaded the vsix, you can install it by pressing F1 and running the command "Install from VSIX". 

Hope this works! 🤞

**Comment by HeidiSteen** [comment] 2021-06-04 16:25
Hi @nturinski (Nathan) -- I don't have permissions to the download site.  Can you zip and send?

**Comment by nturinski** [comment] 2021-06-04 16:28
[vscode-azurestaticwebapps-0.7.1-alpha.zip](https://github.com/microsoft/vscode-azurestaticwebapps/files/6599943/vscode-azurestaticwebapps-0.7.1-alpha.zip)

Oops, sorry about that.  Looks like I can upload it straight to here.

**Comment by HeidiSteen** [comment] 2021-06-04 19:58
@Nturinski @diberry -- Nathan, your fix works great!!  I tried all 3 of our samples (C#, JavaScript, Python).  The steps were the same in all cases, and probably all the same code, but I wanted to be thorough in case there were differences that I'm not aware of.  In all 3 instances, I got the 8-step version of the wizard and had no problems deploying the app.

**Comment by nturinski** [comment] 2021-06-09 21:35
Going to go ahead and close this as it seems to be resolved by removing any git and simple-git calls.

Closed by https://github.com/microsoft/vscode-azurestaticwebapps/pull/408

**Closed by nturinski** 2021-06-09 21:35 UTC

**Comment by nturinski** [comment] 2021-07-08 21:48
@HeidiSteen @diberry Just wanted to let you know that we've released the fix for this issue officially!  The latest version is 0.7.1.
