### ISSUE TITLE
Fail to debug with an error on Mac

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#572] opened 2021-11-09 11:45 UTC
**OS:** Mac
**Build Version:** 20211105.14
**Regression:** Not a regression

**Repro Steps:**

1. Open a Reactsite project in VS Code.
2. Type `cd app` in TERMINAL window -> Type `npm install`.
3. Navigate to "Run and Debug" view -> Select "Azure Static Web Apps…" in the dropdown list -> Select "SWA: Run app"
   -> Start Debugging.
5. Check whether succeed to debug without any error.

**Expect:**
Succeed to debug without any error.

**Actual:**
Fail to debug with an error.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/62053665/140916773-f9ea6e8a-e2be-4110-bdd3-3769548dbdbc.png)

**More Info:**
There are some errors when executing "npm install/sudo npm install" command on Mac. [log.txt](https://github.com/microsoft/vscode-azurestaticwebapps/files/7504360/log.txt)

**Comment by alexweininger** [comment] 2021-11-09 12:35
Hi, which version of VS Code was being used when you encountered this error?

**Comment by v-mengwe** [comment] 2021-11-10 06:45
Thanks for your update. Update the VS Code version from 
```
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```
to 
```
Version: 1.62.1 (Universal)
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T09:23:14.144Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

This issue deesn't reproduce for now. But the browser window doesn't pop up automatically, need to type the address in browser manually.![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/62053665/141042567-5179bc8c-caee-4aac-b8ca-6a9f3c81ee9f.png)

**More Info:**
Pop up a dialog when debugging for the first time, open a webpage https://www.python.org/doc/sunset-python-2/ after clicking "Learn More" button and nothing happens after clicking "OK" button.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/62053665/141042571-bf14efa6-7b9e-4817-b1bd-6435e84becf9.png)

**Comment by alexweininger** [comment] 2021-11-10 17:28
Original bug was fixed by updating VS Code, the suggested now is a duplicate of #571.

**Closed by alexweininger** 2021-11-10 17:28 UTC
Labels: AT-CTI
