### ISSUE TITLE
[Suggestion]Add the logs in "Azure Static Web App(Preview) " for "creating endpoint".

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#68] opened 2020-05-14 09:28 UTC
**OS:** Windows/Mac
**Build Version:** [20200514.4](https://dev.azure.com/ms-azuretools/AzCodePrivate/_build/results?buildId=19336&view=results)

**Repro Steps:**

1. Create a JavaScript project with HttpTrigger function using Functions extension
2. Open this project in VS Code
3. Click the 'Create Endpoint…' button on the ribbon-->JavaScript
4. Check the result

**Actual:**
There is no logs in "Azure Static Web App(Preview) " for "creating endpoint" 
![image](https://user-images.githubusercontent.com/62053665/81914782-534fdd80-9604-11ea-91fa-0880edb0dccb.png)

**Suggestion:**

1. Add the logs in "Azure Static Web App(Preview) " for "creating endpoint" 
2. The prompt message that pops up changes to "Finished creating endpoint..." is better.

**Comment by wwlorey** [comment] 2020-05-20 22:21
Closing as by design. Function triggers in functions don't output anything to the output channel

**Closed by wwlorey** 2020-05-20 22:21 UTC
Labels: AT-CTI, by-design
