### ISSUE TITLE
Create Static Web App command error: `staticWebApps.CreateStaticWebApp` not found

### ISSUE THREAD

**Issue by craigshoemaker** [microsoft/vscode-azurestaticwebapps#734] opened 2022-08-29 17:35 UTC
I am getting a strange error when trying to create a new static web app with the extension.

Here's the steps I followed:

1.	Clone the repo ([Vanilla Basic template repo](https://github.com/staticwebdev/vanilla-basic))
1.	Open the project folder in Visual Studio Code
1.	<kbd>F1</kbd>
1.	Run: **Azure Static Web Apps: Create Static Web App…**

Then I get the following error:

![image](https://user-images.githubusercontent.com/127797/187261605-ba56b477-0afb-47b4-aabf-ba10c59bf04f.png "Command 'Azure Static Web Apps: Create Static Web App...' resulted in an error (command 'staticWebApps.CreateStaticWebApp' not found)")

Here's my system/version info:

### SWA Extension
v0.11.2

### Visual Studio Code
Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

### PC
Processor           11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz   3.30 GHz
Installed RAM    32.0 GB (31.8 GB usable)
Product ID          00330-80000-00000-AA832
System type       64-bit operating system, x64-based processor
Pen and touch   Pen and touch support with 10 touch points

**Comment by alexweininger** [comment] 2022-08-30 23:20
Strange indeed. I can't reproduce this. If you're still experiencing this issue, try reloading your VS Code, or uninstalling and reinstalling the extension.

**Comment by sqeeshy** [comment] 2022-09-13 21:10
I got the same error. Fixed by updating VS Code to latest version (1.71.1 at the moment).

**Closed** 2022-11-09 23:15 UTC
Labels: needs more info
