### ISSUE TITLE
server js

### ISSUE THREAD

**Issue by maksimdev16** [microsoft/vscode-azurestaticwebapps#848] opened 2023-07-09 12:21 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.activate
Error type: string
Error Message: Timed out waiting for authentication provider to register

Version: 0.12.2
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code - Insiders
Product Version: 1.81.0-insider
Language: en

**Comment by nturinski** [comment] 2023-07-19 22:10
Closing as a duplicate of https://github.com/microsoft/vscode-azurestaticwebapps/issues/850

**Closed by nturinski** 2023-07-19 22:10 UTC
