### ISSUE TITLE
Upload local settings is case sensitive When uploading an existing setting

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#284] opened 2020-12-17 09:49 UTC
**OS:** Win 10
**Build Version:** 20201215.1

**Repro steps:**
1. Drill down a static web app --> Expand "Application Settings" node.
2. Add a new setting named "new".
3. Add a new setting named "NEW" --> Prompt "App setting name "NEW" already exists" like below.
![image](https://user-images.githubusercontent.com/57662131/102465940-3f33f900-4089-11eb-89b8-7da9384baa72.png)
4. Upload a setting named "NEW" --> Successfully upload the setting.

**Expect:**
Fail to upload the existing setting and prompt a notification "App setting name "NEW" already exists".

**Actual:**
Succeed to upload an existing setting.
![image](https://user-images.githubusercontent.com/57662131/102466412-f6c90b00-4089-11eb-8b4a-fc0e9a896ac0.png)

**More Info:**
The settings don't have any change after refreshing.

**Comment by nturinski** [comment] 2020-12-17 18:29
Duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/2575.  We leverage the Functions API for upload local settings, so this will be fixed whenever Functions releases.

**Closed by nturinski** 2020-12-17 18:29 UTC
Labels: AT-CTI
