### ISSUE TITLE
There is no "Close Pull Request Job" job in the list when executing command "Azure Static Web Apps: Open Github Action Log" from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#684] opened 2022-05-05 09:29 UTC
**OS:** All
**Azure Resource Extension Build Version:** 20220503.22 (unified)
**Azure Static Web App Extension Build Version:** 20220502.6 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Expand a static web app -> Production -> Action -> Expand an action -> Right click the "Close Pull Request Job" job -> There is a "Open Github Action Log" command in the context menu.
    <img width="413" alt="Screen Shot 2022-05-05 at 16 53 24" src="https://user-images.githubusercontent.com/62053665/166891405-3edbf20f-e779-45a5-b38b-a38992b4f73b.png">
2. F1 -> Azure Static Web Apps: Open Github Action Log -> Select a subscription -> Select a resource -> Select an environment -> Select an action.
3. Check whether there is a "Close Pull Request Job" job in the list or not. 

**Expect:**
There is a "Close Pull Request Job" job in the list.

**Actual:**
There is no "Close Pull Request Job" job in the list.
<img width="287" alt="Screen Shot 2022-05-05 at 16 52 40" src="https://user-images.githubusercontent.com/62053665/166891132-b678dc86-b54a-4498-8f83-23a794121f41.png">

**Comment by alexweininger** [comment] 2022-05-06 20:43
This also reproduces on main so I'm not sure if this is expected or not.

**Comment by alexweininger** [comment] 2022-06-08 22:48
Closing as by design.

**Closed by alexweininger** 2022-06-08 22:48 UTC
Labels: AT-CTI, unified
