### ISSUE TITLE
Fail to create a basic static web app with "Publish local code to a new GitHub repository"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#267] opened 2020-11-25 09:37 UTC
**OS:** All
**Build Version:** 20201125.5

**Repro Steps:**

1. Make sure there is no project opened in VS Code.
2. Right click the Subscription --> Click "Create Static Web App..." --> Select "Publish local code to a new GitHub repository" 
--> Choose a organization --> Select a project to create the new repository --> Enter the name for the new GitHub repository 
--> Select the the privacy (public/private)--> Enter a name for the new Static Web App --> Choose "Custom" build --> Select "Manually ente location" --> Enter "app" --> Default "api" --> Default "build" --> Select a location.
3. Check whether the static web app is created successfully or not.

**Expect:**
The static web app is created successfully.

**Actual:**
Fail to create the static web app with an error.
![image](https://user-images.githubusercontent.com/57662131/100192935-c9c38580-2f2d-11eb-9100-870f499942e8.png)
Details in Output:
```
2:30:58 PM: Creating new public GitHub repository "nicole-test01"...
2:31:01 PM: Created new public GitHub repository "nicole-test01".
2:31:01 PM: Error: Internal error: Expected value to be neither null nor undefined: newRemoteShortname
```

**More Info:**
1. This issue doesn't reproduce when selecting "Use existing GitHub repository".
2. There is an error as below when creating an advanced new static web app.
![image](https://user-images.githubusercontent.com/57662131/100198869-68a0af80-2f37-11eb-8aaa-736ddde4e719.png)
Details in Output:
```
  3:43:35 PM: Creating new public GitHub repository "nicole-test03"...
  3:43:37 PM: Created new public GitHub repository "nicole-test03".
  3:43:37 PM: Error: Failed to execute git
```

**Comment by nturinski** [comment] 2020-11-25 19:46
@v-xinda Nice catch, I should have a fix for the first issue.

But in the more info portion-- do you not have git installed on your test machine?

**Comment by v-xinda** [comment] 2020-11-26 01:29
@nturinski Hi Nathan, I has been installed the git 2.26.1 in my test machine.
![image](https://user-images.githubusercontent.com/57662131/100297198-1ad48780-2fc9-11eb-93a0-8d7c1dc93a0e.png)

**Comment by nturinski** [comment] 2020-11-26 04:32
Could you try again and see if this reproduces?

**Comment by v-xinda** [comment] 2020-11-26 06:22
Verified this issue on the latest build 20201125.13, it still reproduces.
![testgit](https://user-images.githubusercontent.com/57662131/100314810-723b1d80-2ff2-11eb-8c60-ec92e89ab40b.gif)

**Comment by v-xinda** [comment] 2021-03-04 08:52
Verified this issue on the latest build 20210303.1, it still reproduces.

**Comment by nturinski** [comment] 2021-03-22 23:14
I think this error is stemming from the fact that the project you are using already has a git remote origin.  Could you check `git remote -v` and let me know if the remote already exists?

**Comment by v-xinda** [comment] 2021-03-23 08:35
@nturinski  Check the result of the `git remote -v` as below:
1. Open the reactSite folder in vscode.
![image](https://user-images.githubusercontent.com/57662131/112111922-d14f1e80-8bef-11eb-9a70-08eda9673722.png)
2. Open a common project in vscode.
Check the  `git remote -v` of the common project as below:
![image](https://user-images.githubusercontent.com/57662131/112113566-ed53bf80-8bf1-11eb-9b89-30a1e49edd4b.png)
3. No project opens in vscode.
![image](https://user-images.githubusercontent.com/57662131/112115528-3f95e000-8bf4-11eb-968f-e16d622ad19f.png)
I failed to create a basic static web app with "Publish local code to a new GitHub repository" when using a common project which didn't have a a git remote origin.
![create](https://user-images.githubusercontent.com/57662131/112116835-a7005f80-8bf5-11eb-91ee-cb041f6ec36e.gif)

**Comment by nturinski** [comment] 2021-04-27 00:37
This PR https://github.com/microsoft/vscode-azurestaticwebapps/pull/335 will resolve issue 2.  Not sure what exactly is the cause of 1, but I have a feeling having the workspace opened in VS Code might resolve this too.

**Comment by nturinski** [comment] 2021-04-29 01:51
Could you test this again using this build? https://dev.azure.com/ms-azuretools/_apis/resources/Containers/5105878/vsix?itemPath=vsix%2Fvscode-azurestaticwebapps-0.6.1-alpha.vsix  It has better git error handling and that seems to be where the error is coming from.

**Comment by v-xinda** [comment] 2021-04-29 02:51
@nturinski Verified this issue with the above build, must have a git project opens in VS Code to create a static web app. 
![image](https://user-images.githubusercontent.com/57662131/116496701-3e815e00-a8d8-11eb-9123-8feb01f59592.png)
Also, there is no step to select "Publish local code to a new GitHub repository" when creating an advanced static web app. So I can not reproduce this issue.
![basic](https://user-images.githubusercontent.com/57662131/116496914-b780b580-a8d8-11eb-8ee7-2d4b4b13cad2.gif)

**Comment by nturinski** [comment] 2021-04-29 21:54
I'll close this as resolved then since the code path should no longer be possible.

**Closed by nturinski** 2021-04-29 21:54 UTC
Labels: AT-CTI, P1, bug
