### ISSUE TITLE
Add a log 'Uploaded settings to...' in output 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestaticwebapps#76] opened 2020-05-15 07:55 UTC
OS: Windows
Build Version: [20200514.4](https://dev.azure.com/ms-azuretools/AzCodePrivate/_build/results?buildId=19336&view=results)

**Repro Steps:**
1. Right click the Application Settings node for a environment->Upload Local Settings...
2. Check the output log.

**Expect:**
There is a log 'Uploaded settings to...'.

**Actual:**
There isn't a log 'Uploaded settings to...'.
![image](https://user-images.githubusercontent.com/45614674/82025530-0c292180-96c4-11ea-90a0-34968ba0761d.png)

**Comment by wwlorey** [comment] 2020-05-20 22:24
Closing as dupe of https://github.com/microsoft/vscode-azurestaticwebapps/issues/66

**Closed by wwlorey** 2020-05-20 22:24 UTC
Labels: AT-CTI
