### ISSUE TITLE
How to use azure functions that aren't 3.1

### ISSUE THREAD

**Issue by EddieDL** [microsoft/vscode-azurestaticwebapps#628] opened 2022-03-15 16:29 UTC
Can someone help me understand how to use azure functions that aren't 3.1. I see an issue #590 which speaks to this and it is closed, but when you follow the instructions [here](https://docs.microsoft.com/en-us/azure/static-web-apps/add-api?tabs=vanilla-javascript) you get `Unrecognized target framework "netcoreapp3.1"`.

**Comment by wwlorey** [comment] 2022-03-16 22:06
Closing as duplicate of https://github.com/microsoft/vscode-azurestaticwebapps/issues/590. It's fixed in our main branch but has yet to be released. We'll drop a comment on that issue when we release the fix.

**Closed by wwlorey** 2022-03-16 22:06 UTC

**Comment by alexweininger** [comment] 2022-03-24 21:09
Fix has been released in version [0.10.0](https://github.com/microsoft/vscode-azurestaticwebapps/releases/tag/v0.10.0)
