### ISSUE TITLE
Make GitHub optional in the create flow

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#231] opened 2020-10-27 23:31 UTC
This allows creating a SWA that's not connected to GitHub. User can retrieve a token (#230) and use it in an Azure DevOps deployment task, for example.

Needs discussion. /cc @fiveisprime @miwebst

**Comment by annaji-msft** [comment] 2020-10-28 00:13
@anthonychu Can this token be used locally as well and deploy the package right from VSCode? Similar to AppService/Functions.

**Comment by miwebst** [comment] 2020-10-28 00:39
That is a potential option assuming that the host machine can run Docker. Happy to discuss details if that is possible.

**Comment by anthonychu** [comment] 2020-10-28 07:04
The plan is to enable deployment from VS Code at some point.

I am curious about the Docker comment. Was thinking the VS Code extension would know how to zip up the API and app artifact folders and do all the right things to deploy it via the zip API.

**Comment by miwebst** [comment] 2020-10-28 16:30
Yes that is the game plan, was just answering Annaji's comment. Deployment key is only useful if you can run the docker container for uploading. We are still planning to use the zip api.

**Comment by anthonychu** [comment] 2021-04-07 21:07
@fiveisprime Probably needs more discussion because we don't know what people would do in VS Code if they aren't using GitHub. Suggest keeping the VS Code experience GitHub-centric and expand once we figure out what to do. Can we remove from this milestone?

**Comment by nturinski** [comment] 2021-08-03 18:55
Closing as a dupe of https://github.com/microsoft/vscode-azurestaticwebapps/issues/265

**Closed by nturinski** 2021-08-03 18:55 UTC
Labels: tracking
